In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame({
    "Order_ID":[101,102,103,104,105,106,107,108,109,110],
    "Customer":["Amit","Priya","Rahul","Amit","Sneha",
                "Rahul","Neha","Priya","Amit","Sneha"],
    "City":["Mumbai","Pune","Delhi","Mumbai","Pune",
            "Delhi","Nagpur","Pune","Mumbai","Delhi"],
    "Category":["Electronics","Clothing","Electronics",
                "Furniture","Clothing","Electronics",
                "Furniture","Clothing","Electronics","Furniture"],
    "Amount":[5000,2000,np.nan,7000,2500,6000,np.nan,3000,8000,4500],
    "Quantity":[2,1,3,np.nan,2,
                2,1,np.nan,4,2]
})

In [5]:
df

   Order_ID Customer    City     Category  Amount  Quantity
0       101     Amit  Mumbai  Electronics  5000.0       2.0
1       102    Priya    Pune     Clothing  2000.0       1.0
2       103    Rahul   Delhi  Electronics     NaN       3.0
3       104     Amit  Mumbai    Furniture  7000.0       NaN
4       105    Sneha    Pune     Clothing  2500.0       2.0
5       106    Rahul   Delhi  Electronics  6000.0       2.0
6       107     Neha  Nagpur    Furniture     NaN       1.0
7       108    Priya    Pune     Clothing  3000.0       NaN
8       109     Amit  Mumbai  Electronics  8000.0       4.0
9       110    Sneha   Delhi    Furniture  4500.0       2.0

In [6]:
df.isnull()

   Order_ID  Customer   City  Category  Amount  Quantity
0     False     False  False     False   False     False
1     False     False  False     False   False     False
2     False     False  False     False    True     False
3     False     False  False     False   False      True
4     False     False  False     False   False     False
5     False     False  False     False   False     False
6     False     False  False     False    True     False
7     False     False  False     False   False      True
8     False     False  False     False   False     False
9     False     False  False     False   False     False

In [7]:
df["Amount"].isnull()

0    False
1    False
2     True
3    False
4    False
5    False
6     True
7    False
8    False
9    False
Name: Amount, dtype: bool

In [9]:
df.isnull().sum()

Order_ID    0
Customer    0
City        0
Category    0
Amount      2
Quantity    2
dtype: int64

In [10]:
df.dropna()

   Order_ID Customer    City     Category  Amount  Quantity
0       101     Amit  Mumbai  Electronics  5000.0       2.0
1       102    Priya    Pune     Clothing  2000.0       1.0
4       105    Sneha    Pune     Clothing  2500.0       2.0
5       106    Rahul   Delhi  Electronics  6000.0       2.0
8       109     Amit  Mumbai  Electronics  8000.0       4.0
9       110    Sneha   Delhi    Furniture  4500.0       2.0

In [11]:
df.dropna(subset=["Amount"])

   Order_ID Customer    City     Category  Amount  Quantity
0       101     Amit  Mumbai  Electronics  5000.0       2.0
1       102    Priya    Pune     Clothing  2000.0       1.0
3       104     Amit  Mumbai    Furniture  7000.0       NaN
4       105    Sneha    Pune     Clothing  2500.0       2.0
5       106    Rahul   Delhi  Electronics  6000.0       2.0
7       108    Priya    Pune     Clothing  3000.0       NaN
8       109     Amit  Mumbai  Electronics  8000.0       4.0
9       110    Sneha   Delhi    Furniture  4500.0       2.0

In [13]:
df["Amount"]=df["Amount"].fillna(0)
df

   Order_ID Customer    City     Category  Amount  Quantity
0       101     Amit  Mumbai  Electronics  5000.0       2.0
1       102    Priya    Pune     Clothing  2000.0       1.0
2       103    Rahul   Delhi  Electronics     0.0       3.0
3       104     Amit  Mumbai    Furniture  7000.0       NaN
4       105    Sneha    Pune     Clothing  2500.0       2.0
5       106    Rahul   Delhi  Electronics  6000.0       2.0
6       107     Neha  Nagpur    Furniture     0.0       1.0
7       108    Priya    Pune     Clothing  3000.0       NaN
8       109     Amit  Mumbai  Electronics  8000.0       4.0
9       110    Sneha   Delhi    Furniture  4500.0       2.0

In [16]:
mean_amount = df["Quantity"].mean()
df["Quantity"] = df["Quantity"].fillna(mean_amount)
df

   Order_ID Customer    City     Category  Amount  Quantity
0       101     Amit  Mumbai  Electronics  5000.0     2.000
1       102    Priya    Pune     Clothing  2000.0     1.000
2       103    Rahul   Delhi  Electronics     0.0     3.000
3       104     Amit  Mumbai    Furniture  7000.0     2.125
4       105    Sneha    Pune     Clothing  2500.0     2.000
5       106    Rahul   Delhi  Electronics  6000.0     2.000
6       107     Neha  Nagpur    Furniture     0.0     1.000
7       108    Priya    Pune     Clothing  3000.0     2.125
8       109     Amit  Mumbai  Electronics  8000.0     4.000
9       110    Sneha   Delhi    Furniture  4500.0     2.000

In [ ]:
df["Amount"] = df["Amount"].ffill() # forward fill filles last value
df["Amount"] = df["Amount"].bfill() # backward fill filles last value

In [19]:
df["Amount"] = df["Amount"].fillna(df["Amount"].median())

df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())

In [20]:
df.isnull().sum()

Order_ID    0
Customer    0
City        0
Category    0
Amount      0
Quantity    0
dtype: int64

In [21]:
df.groupby("City")["Amount"].sum()

City
Delhi     10500.0
Mumbai    20000.0
Nagpur        0.0
Pune       7500.0
Name: Amount, dtype: float64

In [24]:
grouped = df.groupby("City")
print(grouped)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001B6552536F0>

In [25]:
df.groupby("City")["Amount"].mean()

City
Delhi     3500.000000
Mumbai    6666.666667
Nagpur       0.000000
Pune      2500.000000
Name: Amount, dtype: float64

In [27]:
df.groupby("City")["Order_ID"].count()

City
Delhi     3
Mumbai    3
Nagpur    1
Pune      3
Name: Order_ID, dtype: int64

In [28]:
df.groupby("City")["Amount"].agg(["sum","mean","max","min"])

            sum         mean     max     min
City
Delhi   10500.0  3500.000000  6000.0     0.0
Mumbai  20000.0  6666.666667  8000.0  5000.0
Nagpur      0.0     0.000000     0.0     0.0
Pune     7500.0  2500.000000  3000.0  2000.0

In [29]:
df.groupby(["City","Category"])["Amount"].sum()

City    Category
Delhi   Electronics     6000.0
        Furniture       4500.0
Mumbai  Electronics    13000.0
        Furniture       7000.0
Nagpur  Furniture          0.0
Pune    Clothing        7500.0
Name: Amount, dtype: float64

In [30]:
df.groupby("City").size()

City
Delhi     3
Mumbai    3
Nagpur    1
Pune      3
dtype: int64

In [32]:
df.groupby("City")["Amount"].count()

City
Delhi     3
Mumbai    3
Nagpur    1
Pune      3
Name: Amount, dtype: int64

In [33]:
def sales_range(x):
    return x.max() - x.min()

df.groupby("City")["Amount"].apply(sales_range)

City
Delhi     6000.0
Mumbai    3000.0
Nagpur       0.0
Pune      1000.0
Name: Amount, dtype: float64

In [34]:
df.groupby("City").agg({
    "Amount":["sum","mean"],
    "Quantity":["sum","mean"]
})

         Amount              Quantity
            sum         mean      sum      mean
City
Delhi   10500.0  3500.000000    7.000  2.333333
Mumbai  20000.0  6666.666667    8.125  2.708333
Nagpur      0.0     0.000000    1.000  1.000000
Pune     7500.0  2500.000000    5.125  1.708333

In [2]:
import pandas as pd

customers = pd.DataFrame({
    "customer_id":[1,2,3,4,5],
    "name":["Amit","Priya","Rahul","Sneha","Neha"],
    "city":["Mumbai","Pune","Delhi","Pune","Nagpur"]
})

customers

   customer_id   name    city
0            1   Amit  Mumbai
1            2  Priya    Pune
2            3  Rahul   Delhi
3            4  Sneha    Pune
4            5   Neha  Nagpur

In [3]:
orders = pd.DataFrame({
    "order_id":[101,102,103,104,105],
    "customer_id":[1,2,2,3,1],
    "Amount":[5000,2000,3000,4000,6000]
})

orders

   order_id  customer_id  Amount
0       101            1    5000
1       102            2    2000
2       103            2    3000
3       104            3    4000
4       105            1    6000

In [4]:
pd.merge(
    customers,
    orders,
    on="customer_id",
    how="inner"
)

   customer_id   name    city  order_id  Amount
0            1   Amit  Mumbai       101    5000
1            1   Amit  Mumbai       105    6000
2            2  Priya    Pune       102    2000
3            2  Priya    Pune       103    3000
4            3  Rahul   Delhi       104    4000

In [5]:
pd.merge(
    customers,
    orders,
    on="customer_id",
    how = "left"
)

   customer_id   name    city  order_id  Amount
0            1   Amit  Mumbai     101.0  5000.0
1            1   Amit  Mumbai     105.0  6000.0
2            2  Priya    Pune     102.0  2000.0
3            2  Priya    Pune     103.0  3000.0
4            3  Rahul   Delhi     104.0  4000.0
5            4  Sneha    Pune       NaN     NaN
6            5   Neha  Nagpur       NaN     NaN

In [6]:
pd.merge(
    customers,
    orders,
    on="customer_id",
    how="right"
)

   customer_id   name    city  order_id  Amount
0            1   Amit  Mumbai       101    5000
1            2  Priya    Pune       102    2000
2            2  Priya    Pune       103    3000
3            3  Rahul   Delhi       104    4000
4            1   Amit  Mumbai       105    6000

In [8]:
pd.merge(
    customers,
    orders,
    on="customer_id",
    how="outer"
)

   customer_id   name    city  order_id  Amount
0            1   Amit  Mumbai     101.0  5000.0
1            1   Amit  Mumbai     105.0  6000.0
2            2  Priya    Pune     102.0  2000.0
3            2  Priya    Pune     103.0  3000.0
4            3  Rahul   Delhi     104.0  4000.0
5            4  Sneha    Pune       NaN     NaN
6            5   Neha  Nagpur       NaN     NaN

In [9]:
customers=pd.DataFrame({
    "cust_id":[1,2,3]
})

orders=pd.DataFrame({
    "customer_id":[1,2,3]
})

pd.merge(
    customers,
    orders,
    left_on="cust_id",
    right_on="customer_id"
)

   cust_id  customer_id
0        1            1
1        2            2
2        3            3

In [13]:
df1 = pd.DataFrame({
    "name":["Amit","Priya"]
},index=[1,2])

df2 = pd.DataFrame(
    {"Salary":[50000,60000]},index=[1,2]
)

pd.merge(df1,df2,left_index=True,right_index=True)

    name  Salary
1   Amit   50000
2  Priya   60000

In [16]:
jan=pd.DataFrame({
    "Employee":["Amit","Priya"],
    "Sales":[5000,6000]
})

feb = pd.DataFrame({
    "Employee":["Amit","Priya"],
    "Sales":[7000,8000]
})  

pd.concat([jan,feb],ignore_index=True)

  Employee  Sales
0     Amit   5000
1    Priya   6000
2     Amit   7000
3    Priya   8000

In [4]:
import pandas as pd

name=pd.DataFrame({
    "name":["Amit","Priya"]
})

salary = pd.DataFrame({
    "salary":[50000,60000]
})

pd.concat(
    [name,salary],axis=1
)

    name  salary
0   Amit   50000
1  Priya   60000

In [3]:
sales = pd.DataFrame({
    "city":["mumbai","pune","pune","mumbai","delhi"],
    "category":["mobile","laptop","mobile","laptop","mobile"],
    "revenue":[5000,7000,6000,8000,4500]
})

sales.pivot_table(
    values="revenue",
    index="city",
    columns="category",
    aggfunc="sum"
)

category  laptop  mobile
city
delhi        NaN  4500.0
mumbai    8000.0  5000.0
pune      7000.0  6000.0

In [4]:
import pandas as pd

sales.pivot_table(
    values = "revenue",
    index="city",
    columns = "category",
    aggfunc=["sum",'mean']
)

             sum            mean
category  laptop  mobile  laptop  mobile
city
delhi        NaN  4500.0     NaN  4500.0
mumbai    8000.0  5000.0  8000.0  5000.0
pune      7000.0  6000.0  7000.0  6000.0

In [6]:
employees = pd.DataFrame({
    "name":["amit","priya","rahul"],
    "salary":[50000,60000,55000]
})

employees["salary"].apply(lambda x: x*1.5)

0    75000.0
1    90000.0
2    82500.0
Name: salary, dtype: float64

In [8]:
employees["bonus"] = employees["salary"].apply(lambda x:x*0.1)

In [9]:
employees

    name  salary   bonus
0   amit   50000  5000.0
1  priya   60000  6000.0
2  rahul   55000  5500.0

In [10]:
dept = pd.Series([
    "IT","HR","Finance"
])

In [13]:
dept.map({
    "IT":"tech",
    "HR":"human resources",
    "Finance":"finance"
})

0               tech
1    human resources
2            finance
dtype: str

In [11]:
import pandas as pd

df = pd.DataFrame({
    "order_id":[101,102,103,104,105,106],
    "customer":["amit","priya","rahul","amit","sneha","vikas"],
    "amount":[5000,2000,3000,7000,2500,6000],
    "order_date":["2023-11-01","2023-06-21","2023-12-03",
                "2023-02-04","2023-01-05","2023-03-06"]
})

print(df)

   order_id customer  amount  order_date
0       101     amit    5000  2023-11-01
1       102    priya    2000  2023-06-21
2       103    rahul    3000  2023-12-03
3       104     amit    7000  2023-02-04
4       105    sneha    2500  2023-01-05
5       106    vikas    6000  2023-03-06

In [12]:
df["order_date"] = pd.to_datetime(df["order_date"])
print(df["order_date"])

0   2023-11-01
1   2023-06-21
2   2023-12-03
3   2023-02-04
4   2023-01-05
5   2023-03-06
Name: order_date, dtype: datetime64[us]

In [13]:
df["year"] = df["order_date"].dt.year
print(df[["order_date","year"]])

  order_date  year
0 2023-11-01  2023
1 2023-06-21  2023
2 2023-12-03  2023
3 2023-02-04  2023
4 2023-01-05  2023
5 2023-03-06  2023

In [14]:
df["month"] = df["order_date"].dt.month 
df["day"] = df["order_date"].dt.day
print(df[["order_date","month","day"]])

  order_date  month  day
0 2023-11-01     11    1
1 2023-06-21      6   21
2 2023-12-03     12    3
3 2023-02-04      2    4
4 2023-01-05      1    5
5 2023-03-06      3    6

In [15]:
df["month_name"] = df["order_date"].dt.month_name()
print(df[["order_date","month_name"]])

  order_date month_name
0 2023-11-01   November
1 2023-06-21       June
2 2023-12-03   December
3 2023-02-04   February
4 2023-01-05    January
5 2023-03-06      March

In [16]:
df["quarter"] = df["order_date"].dt.quarter
print(df[["order_date","quarter"]])

  order_date  quarter
0 2023-11-01        4
1 2023-06-21        2
2 2023-12-03        4
3 2023-02-04        1
4 2023-01-05        1
5 2023-03-06        1

In [17]:
df["week"] = df["order_date"].dt.isocalendar().week
print(df[["order_date","week"]])

  order_date  week
0 2023-11-01    44
1 2023-06-21    25
2 2023-12-03    48
3 2023-02-04     5
4 2023-01-05     1
5 2023-03-06    10

In [18]:
df[df["order_date"] > "2023-02-01"]

,order_id,customer,amount,order_date,year,month,day,month_name,quarter,week
0,101,amit,5000,2023-11-01,2023,11,1,November,4,44
1,102,priya,2000,2023-06-21,2023,6,21,June,2,25
2,103,rahul,3000,2023-12-03,2023,12,3,December,4,48
3,104,amit,7000,2023-02-04,2023,2,4,February,1,5
5,106,vikas,6000,2023-03-06,2023,3,6,March,1,10

In [21]:
df["delivery_date"] = (
    df["order_date"] + pd.Timedelta(days=7)
)

print(df[["order_date","delivery_date"]])

  order_date delivery_date
0 2023-11-01    2023-11-08
1 2023-06-21    2023-06-28
2 2023-12-03    2023-12-10
3 2023-02-04    2023-02-11
4 2023-01-05    2023-01-12
5 2023-03-06    2023-03-13

In [23]:
df["days_to_delivery"] = (df["delivery_date"] - df["order_date"])
print(df[["order_date","delivery_date","days_to_delivery"]])

  order_date delivery_date days_to_delivery
0 2023-11-01    2023-11-08           7 days
1 2023-06-21    2023-06-28           7 days
2 2023-12-03    2023-12-10           7 days
3 2023-02-04    2023-02-11           7 days
4 2023-01-05    2023-01-12           7 days
5 2023-03-06    2023-03-13           7 days

In [26]:
today = pd.Timestamp.today()
df["order_age"] = today - df["order_date"]
print(today)
print(df[["order_date","order_age"]])

2026-06-06 18:09:03.531326
  order_date                 order_age
0 2023-11-01  948 days 18:09:03.531326
1 2023-06-21 1081 days 18:09:03.531326
2 2023-12-03  916 days 18:09:03.531326
3 2023-02-04 1218 days 18:09:03.531326
4 2023-01-05 1248 days 18:09:03.531326
5 2023-03-06 1188 days 18:09:03.531326

In [27]:
pd.date_range(start="2025-01-01",end="2025-04-04")

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10', '2025-01-11', '2025-01-12',
               '2025-01-13', '2025-01-14', '2025-01-15', '2025-01-16',
               '2025-01-17', '2025-01-18', '2025-01-19', '2025-01-20',
               '2025-01-21', '2025-01-22', '2025-01-23', '2025-01-24',
               '2025-01-25', '2025-01-26', '2025-01-27', '2025-01-28',
               '2025-01-29', '2025-01-30', '2025-01-31', '2025-02-01',
               '2025-02-02', '2025-02-03', '2025-02-04', '2025-02-05',
               '2025-02-06', '2025-02-07', '2025-02-08', '2025-02-09',
               '2025-02-10', '2025-02-11', '2025-02-12', '2025-02-13',
               '2025-02-14', '2025-02-15', '2025-02-16', '2025-02-17',
               '2025-02-18', '2025-02-19', '2025-02-20', '2025-02-21',
               '2025-02-22', '2025-02-23', '2025-02-24', '2025-02-25',
               '2025-02-26', '2025-02-27', '2025-02-28', '2025-03-01',
               '2025-03-02', '2025-03-03', '2025-03-04', '2025-03-05',
               '2025-03-06', '2025-03-07', '2025-03-08', '2025-03-09',
               '2025-03-10', '2025-03-11', '2025-03-12', '2025-03-13',
               '2025-03-14', '2025-03-15', '2025-03-16', '2025-03-17',
               '2025-03-18', '2025-03-19', '2025-03-20', '2025-03-21',
               '2025-03-22', '2025-03-23', '2025-03-24', '2025-03-25',
               '2025-03-26', '2025-03-27', '2025-03-28', '2025-03-29',
               '2025-03-30', '2025-03-31', '2025-04-01', '2025-04-02',
               '2025-04-03', '2025-04-04'],
              dtype='datetime64[us]', freq='D')

In [28]:
sales = pd.DataFrame({
    "Date":[
        "2025-01-01",
        "2025-01-02",
        "2025-01-03",
        "2025-01-04",
        "2025-01-05"
    ],
    "Revenue":[
        1000,
        1500,
        1200,
        1800,
        1300
    ]
})

In [31]:
sales["date"] = pd.to_datetime(
    sales["Date"]
)
print(sales)

         Date  Revenue       date
0  2025-01-01     1000 2025-01-01
1  2025-01-02     1500 2025-01-02
2  2025-01-03     1200 2025-01-03
3  2025-01-04     1800 2025-01-04
4  2025-01-05     1300 2025-01-05

In [37]:
sales.set_index("date",inplace=True)
print(sales)

            Revenue
date
2025-01-01     1000
2025-01-02     1500
2025-01-03     1200
2025-01-04     1800
2025-01-05     1300

In [40]:
sales.resample("M").sum()

ValueError: Invalid frequency: M. Failed to parse with error message: ValueError("'M' is no longer supported for offsets. Please use 'ME' instead.")

In [42]:
sales.resample("D").mean()

            Revenue
date
2025-01-01   1000.0
2025-01-02   1500.0
2025-01-03   1200.0
2025-01-04   1800.0
2025-01-05   1300.0

In [44]:
orders = pd.DataFrame({
    "Order_ID":[1,2,3,4,5,6],
    "Customer":["Amit","Priya","Rahul",
                "Amit","Sneha","Rahul"],
    "Category":["Mobile","Laptop","Mobile",
                "Laptop","Mobile","Laptop"],
    "Revenue":[5000,7000,3000,
               8000,4000,6000],
    "Order_Date":[
        "2025-01-10",
        "2025-01-20",
        "2025-02-05",
        "2025-02-15",
        "2025-03-10",
        "2025-03-22"
    ]
})

print(orders)

   Order_ID Customer Category  Revenue  Order_Date
0         1     Amit   Mobile     5000  2025-01-10
1         2    Priya   Laptop     7000  2025-01-20
2         3    Rahul   Mobile     3000  2025-02-05
3         4     Amit   Laptop     8000  2025-02-15
4         5    Sneha   Mobile     4000  2025-03-10
5         6    Rahul   Laptop     6000  2025-03-22

In [46]:
orders["Order_Date"] = pd.to_datetime(orders["Order_Date"])

In [49]:
orders["month"] = orders["Order_Date"].dt.month_name()
print(orders[["Order_Date","month"]])

  Order_Date     month
0 2025-01-10   January
1 2025-01-20   January
2 2025-02-05  February
3 2025-02-15  February
4 2025-03-10     March
5 2025-03-22     March

In [50]:
orders.groupby("month")["Revenue"].sum()

month
February    11000
January     12000
March       10000
Name: Revenue, dtype: int64

In [51]:
orders.groupby("Category")["Revenue"].sum()

Category
Laptop    21000
Mobile    12000
Name: Revenue, dtype: int64

In [52]:
orders.groupby("Customer")["Revenue"].sum().sort_values(ascending=False)

Customer
Amit     13000
Rahul     9000
Priya     7000
Sneha     4000
Name: Revenue, dtype: int64

In [53]:
orders.pivot_table(
    values="Revenue",
    index = "Customer",
    columns = "Category",
    aggfunc="sum"
)

Category  Laptop  Mobile
Customer
Amit      8000.0  5000.0
Priya     7000.0     NaN
Rahul     6000.0  3000.0
Sneha        NaN  4000.0