In [1]:
import pandas as pd
import numpy as np

In [8]:
my_series = pd.Series(data=[1,2,3,4],index=['a','b','c','d'])
my_series

a    1
b    2
c    3
d    4
dtype: int64

In [9]:
my_dict = {"x":2,"a":5,"b":4,"c":8}
my_series2 = pd.Series(my_dict)
my_series2

x    2
a    5
b    4
c    8
dtype: int64

In [11]:
print(my_series["a"])

1

In [15]:
print(my_series2.iloc[0])

2

In [16]:
my_series[1:3]

b    2
c    3
dtype: int64

In [19]:
my_series + my_series

a    2
b    4
c    6
d    8
dtype: int64

In [20]:
my_series + my_series2

a     6.0
b     6.0
c    11.0
d     NaN
x     NaN
dtype: float64

In [23]:
print(np.mean(my_series))
print(np.mean(my_series2))

2.5
4.75

In [24]:
my_dict = {"name":["Joe","Bob","Frans"],
           "age":np.array([10,15,20]),
           "weight":(75,123,239),
           "height":pd.Series([4.5,6.7,6.6],
                              index = ["joe","bob","frans"]),
           "siblings": 1,
           "gender":"M"}

df = pd.DataFrame(my_dict)
df

        name  age  weight  height  siblings gender
joe      Joe   10      75     4.5         1      M
bob      Bob   15     123     6.7         1      M
frans  Frans   20     239     6.6         1      M

In [25]:
df2 = pd.DataFrame(my_dict,index = my_dict["name"])
df2

        name  age  weight  height  siblings gender
Joe      Joe   10      75     NaN         1      M
Bob      Bob   15     123     NaN         1      M
Frans  Frans   20     239     NaN         1      M

In [26]:
df2["weight"]

Joe       75
Bob      123
Frans    239
Name: weight, dtype: int64

In [27]:
df2.weight

Joe       75
Bob      123
Frans    239
Name: weight, dtype: int64

In [28]:
del df2['name']

In [29]:
df2["IQ"] = [120,123,334]
df2

       age  weight  height  siblings gender   IQ
Joe     10      75     NaN         1      M  120
Bob     15     123     NaN         1      M  123
Frans   20     239     NaN         1      M  334

In [30]:
df2["married"] = False
df2

       age  weight  height  siblings gender   IQ  married
Joe     10      75     NaN         1      M  120    False
Bob     15     123     NaN         1      M  123    False
Frans   20     239     NaN         1      M  334    False

In [32]:
df2["College"] = pd.Series(["harvard"],index = ["Joe"])
df2

       age  weight  height  siblings gender   IQ  married  College
Joe     10      75     NaN         1      M  120    False  harvard
Bob     15     123     NaN         1      M  123    False      NaN
Frans   20     239     NaN         1      M  334    False      NaN

In [33]:
df2.loc["Joe"]

age              10
weight           75
height          NaN
siblings          1
gender            M
IQ              120
married       False
College     harvard
Name: Joe, dtype: object

In [34]:
df2.loc["Joe","IQ"]

np.int64(120)

In [35]:
df2.loc["Joe":"Bob","IQ":"College"]

      IQ  married  College
Joe  120    False  harvard
Bob  123    False      NaN

In [ ]:
df2.iloc[0]

     age  weight  height  siblings gender   IQ  married  College
Joe   10      75     NaN         1      M  120    False  harvard
Bob   15     123     NaN         1      M  123    False      NaN

In [38]:
df2.iloc[0:2,5:8]

      IQ  married  College
Joe  120    False  harvard
Bob  123    False      NaN

In [39]:
boolean_index = [False,True,True]

df2[boolean_index]

       age  weight  height  siblings gender   IQ  married College
Bob     15     123     NaN         1      M  123    False     NaN
Frans   20     239     NaN         1      M  334    False     NaN

In [40]:
boolean_index = df2["age"] > 12
df2[boolean_index]

       age  weight  height  siblings gender   IQ  married College
Bob     15     123     NaN         1      M  123    False     NaN
Frans   20     239     NaN         1      M  334    False     NaN

In [41]:
df2[df2["age"] > 12]

       age  weight  height  siblings gender   IQ  married College
Bob     15     123     NaN         1      M  123    False     NaN
Frans   20     239     NaN         1      M  334    False     NaN