In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame({
    "Order_ID":[101,102,103,104,105,106,107,108,109,110],
    "Customer":["Amit","Priya","Rahul","Amit","Sneha",
                "Rahul","Neha","Priya","Amit","Sneha"],
    "City":["Mumbai","Pune","Delhi","Mumbai","Pune",
            "Delhi","Nagpur","Pune","Mumbai","Delhi"],
    "Category":["Electronics","Clothing","Electronics",
                "Furniture","Clothing","Electronics",
                "Furniture","Clothing","Electronics","Furniture"],
    "Amount":[5000,2000,np.nan,7000,2500,6000,np.nan,3000,8000,4500],
    "Quantity":[2,1,3,np.nan,2,
                2,1,np.nan,4,2]
})

In [5]:
df

   Order_ID Customer    City     Category  Amount  Quantity
0       101     Amit  Mumbai  Electronics  5000.0       2.0
1       102    Priya    Pune     Clothing  2000.0       1.0
2       103    Rahul   Delhi  Electronics     NaN       3.0
3       104     Amit  Mumbai    Furniture  7000.0       NaN
4       105    Sneha    Pune     Clothing  2500.0       2.0
5       106    Rahul   Delhi  Electronics  6000.0       2.0
6       107     Neha  Nagpur    Furniture     NaN       1.0
7       108    Priya    Pune     Clothing  3000.0       NaN
8       109     Amit  Mumbai  Electronics  8000.0       4.0
9       110    Sneha   Delhi    Furniture  4500.0       2.0

In [6]:
df.isnull()

   Order_ID  Customer   City  Category  Amount  Quantity
0     False     False  False     False   False     False
1     False     False  False     False   False     False
2     False     False  False     False    True     False
3     False     False  False     False   False      True
4     False     False  False     False   False     False
5     False     False  False     False   False     False
6     False     False  False     False    True     False
7     False     False  False     False   False      True
8     False     False  False     False   False     False
9     False     False  False     False   False     False

In [7]:
df["Amount"].isnull()

0    False
1    False
2     True
3    False
4    False
5    False
6     True
7    False
8    False
9    False
Name: Amount, dtype: bool

In [9]:
df.isnull().sum()

Order_ID    0
Customer    0
City        0
Category    0
Amount      2
Quantity    2
dtype: int64

In [10]:
df.dropna()

   Order_ID Customer    City     Category  Amount  Quantity
0       101     Amit  Mumbai  Electronics  5000.0       2.0
1       102    Priya    Pune     Clothing  2000.0       1.0
4       105    Sneha    Pune     Clothing  2500.0       2.0
5       106    Rahul   Delhi  Electronics  6000.0       2.0
8       109     Amit  Mumbai  Electronics  8000.0       4.0
9       110    Sneha   Delhi    Furniture  4500.0       2.0

In [11]:
df.dropna(subset=["Amount"])

   Order_ID Customer    City     Category  Amount  Quantity
0       101     Amit  Mumbai  Electronics  5000.0       2.0
1       102    Priya    Pune     Clothing  2000.0       1.0
3       104     Amit  Mumbai    Furniture  7000.0       NaN
4       105    Sneha    Pune     Clothing  2500.0       2.0
5       106    Rahul   Delhi  Electronics  6000.0       2.0
7       108    Priya    Pune     Clothing  3000.0       NaN
8       109     Amit  Mumbai  Electronics  8000.0       4.0
9       110    Sneha   Delhi    Furniture  4500.0       2.0

In [13]:
df["Amount"]=df["Amount"].fillna(0)
df

   Order_ID Customer    City     Category  Amount  Quantity
0       101     Amit  Mumbai  Electronics  5000.0       2.0
1       102    Priya    Pune     Clothing  2000.0       1.0
2       103    Rahul   Delhi  Electronics     0.0       3.0
3       104     Amit  Mumbai    Furniture  7000.0       NaN
4       105    Sneha    Pune     Clothing  2500.0       2.0
5       106    Rahul   Delhi  Electronics  6000.0       2.0
6       107     Neha  Nagpur    Furniture     0.0       1.0
7       108    Priya    Pune     Clothing  3000.0       NaN
8       109     Amit  Mumbai  Electronics  8000.0       4.0
9       110    Sneha   Delhi    Furniture  4500.0       2.0

In [16]:
mean_amount = df["Quantity"].mean()
df["Quantity"] = df["Quantity"].fillna(mean_amount)
df

   Order_ID Customer    City     Category  Amount  Quantity
0       101     Amit  Mumbai  Electronics  5000.0     2.000
1       102    Priya    Pune     Clothing  2000.0     1.000
2       103    Rahul   Delhi  Electronics     0.0     3.000
3       104     Amit  Mumbai    Furniture  7000.0     2.125
4       105    Sneha    Pune     Clothing  2500.0     2.000
5       106    Rahul   Delhi  Electronics  6000.0     2.000
6       107     Neha  Nagpur    Furniture     0.0     1.000
7       108    Priya    Pune     Clothing  3000.0     2.125
8       109     Amit  Mumbai  Electronics  8000.0     4.000
9       110    Sneha   Delhi    Furniture  4500.0     2.000

In [ ]:
df["Amount"] = df["Amount"].ffill() # forward fill filles last value
df["Amount"] = df["Amount"].bfill() # backward fill filles last value

In [19]:
df["Amount"] = df["Amount"].fillna(df["Amount"].median())

df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())

In [20]:
df.isnull().sum()

Order_ID    0
Customer    0
City        0
Category    0
Amount      0
Quantity    0
dtype: int64

In [21]:
df.groupby("City")["Amount"].sum()

City
Delhi     10500.0
Mumbai    20000.0
Nagpur        0.0
Pune       7500.0
Name: Amount, dtype: float64

In [24]:
grouped = df.groupby("City")
print(grouped)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001B6552536F0>

In [25]:
df.groupby("City")["Amount"].mean()

City
Delhi     3500.000000
Mumbai    6666.666667
Nagpur       0.000000
Pune      2500.000000
Name: Amount, dtype: float64

In [27]:
df.groupby("City")["Order_ID"].count()

City
Delhi     3
Mumbai    3
Nagpur    1
Pune      3
Name: Order_ID, dtype: int64

In [28]:
df.groupby("City")["Amount"].agg(["sum","mean","max","min"])

            sum         mean     max     min
City
Delhi   10500.0  3500.000000  6000.0     0.0
Mumbai  20000.0  6666.666667  8000.0  5000.0
Nagpur      0.0     0.000000     0.0     0.0
Pune     7500.0  2500.000000  3000.0  2000.0

In [29]:
df.groupby(["City","Category"])["Amount"].sum()

City    Category
Delhi   Electronics     6000.0
        Furniture       4500.0
Mumbai  Electronics    13000.0
        Furniture       7000.0
Nagpur  Furniture          0.0
Pune    Clothing        7500.0
Name: Amount, dtype: float64

In [30]:
df.groupby("City").size()

City
Delhi     3
Mumbai    3
Nagpur    1
Pune      3
dtype: int64

In [32]:
df.groupby("City")["Amount"].count()

City
Delhi     3
Mumbai    3
Nagpur    1
Pune      3
Name: Amount, dtype: int64

In [33]:
def sales_range(x):
    return x.max() - x.min()

df.groupby("City")["Amount"].apply(sales_range)

City
Delhi     6000.0
Mumbai    3000.0
Nagpur       0.0
Pune      1000.0
Name: Amount, dtype: float64

In [34]:
df.groupby("City").agg({
    "Amount":["sum","mean"],
    "Quantity":["sum","mean"]
})

         Amount              Quantity
            sum         mean      sum      mean
City
Delhi   10500.0  3500.000000    7.000  2.333333
Mumbai  20000.0  6666.666667    8.125  2.708333
Nagpur      0.0     0.000000    1.000  1.000000
Pune     7500.0  2500.000000    5.125  1.708333

In [2]:
import pandas as pd

customers = pd.DataFrame({
    "customer_id":[1,2,3,4,5],
    "name":["Amit","Priya","Rahul","Sneha","Neha"],
    "city":["Mumbai","Pune","Delhi","Pune","Nagpur"]
})

customers

   customer_id   name    city
0            1   Amit  Mumbai
1            2  Priya    Pune
2            3  Rahul   Delhi
3            4  Sneha    Pune
4            5   Neha  Nagpur

In [3]:
orders = pd.DataFrame({
    "order_id":[101,102,103,104,105],
    "customer_id":[1,2,2,3,1],
    "Amount":[5000,2000,3000,4000,6000]
})

orders

   order_id  customer_id  Amount
0       101            1    5000
1       102            2    2000
2       103            2    3000
3       104            3    4000
4       105            1    6000

In [4]:
pd.merge(
    customers,
    orders,
    on="customer_id",
    how="inner"
)

   customer_id   name    city  order_id  Amount
0            1   Amit  Mumbai       101    5000
1            1   Amit  Mumbai       105    6000
2            2  Priya    Pune       102    2000
3            2  Priya    Pune       103    3000
4            3  Rahul   Delhi       104    4000

In [5]:
pd.merge(
    customers,
    orders,
    on="customer_id",
    how = "left"
)

   customer_id   name    city  order_id  Amount
0            1   Amit  Mumbai     101.0  5000.0
1            1   Amit  Mumbai     105.0  6000.0
2            2  Priya    Pune     102.0  2000.0
3            2  Priya    Pune     103.0  3000.0
4            3  Rahul   Delhi     104.0  4000.0
5            4  Sneha    Pune       NaN     NaN
6            5   Neha  Nagpur       NaN     NaN

In [6]:
pd.merge(
    customers,
    orders,
    on="customer_id",
    how="right"
)

   customer_id   name    city  order_id  Amount
0            1   Amit  Mumbai       101    5000
1            2  Priya    Pune       102    2000
2            2  Priya    Pune       103    3000
3            3  Rahul   Delhi       104    4000
4            1   Amit  Mumbai       105    6000

In [8]:
pd.merge(
    customers,
    orders,
    on="customer_id",
    how="outer"
)

   customer_id   name    city  order_id  Amount
0            1   Amit  Mumbai     101.0  5000.0
1            1   Amit  Mumbai     105.0  6000.0
2            2  Priya    Pune     102.0  2000.0
3            2  Priya    Pune     103.0  3000.0
4            3  Rahul   Delhi     104.0  4000.0
5            4  Sneha    Pune       NaN     NaN
6            5   Neha  Nagpur       NaN     NaN

In [9]:
customers=pd.DataFrame({
    "cust_id":[1,2,3]
})

orders=pd.DataFrame({
    "customer_id":[1,2,3]
})

pd.merge(
    customers,
    orders,
    left_on="cust_id",
    right_on="customer_id"
)

   cust_id  customer_id
0        1            1
1        2            2
2        3            3

In [13]:
df1 = pd.DataFrame({
    "name":["Amit","Priya"]
},index=[1,2])

df2 = pd.DataFrame(
    {"Salary":[50000,60000]},index=[1,2]
)

pd.merge(df1,df2,left_index=True,right_index=True)

    name  Salary
1   Amit   50000
2  Priya   60000

In [16]:
jan=pd.DataFrame({
    "Employee":["Amit","Priya"],
    "Sales":[5000,6000]
})

feb = pd.DataFrame({
    "Employee":["Amit","Priya"],
    "Sales":[7000,8000]
})  

pd.concat([jan,feb],ignore_index=True)

  Employee  Sales
0     Amit   5000
1    Priya   6000
2     Amit   7000
3    Priya   8000

In [17]:
names=pd.DataFrame({
    "name":["Amit","Priya"]
})

salary = pd.DataFrame({
    "salary":[50000,60000]
})

pd.concat(
    [name,salary],axis=1
)

NameError: name 'name' is not defined